Increase CF-java-client log level
To diagnose CreateAsyncInstanceWithBackingServiceKeysAcceptanceTest. deployAppsAndCreateServiceKeysOnBindService() failure:
java.lang.IllegalArgumentException: Service instance 2308b671-0c63-4542-866e-7249a8d564a3 does not exist
	at org.cloudfoundry.util.ExceptionUtils.illegalArgument(ExceptionUtils.java:45)

I.e. backing service not available after async brokered service provisioning completes.