Incomplete attempt to complete wiremock mock:
05-11-2019 16:02:26.912 [cloudfoundry-client-nio-1] DEBUG cloudfoundry-client.response.lambda$null$7 - 200    http://localhost:8080/v2/spaces/TEST-SPACE-GUID/service_instances?q=name:my-db-service&page=1&return_user_provided_service_instances=true (42 ms)
05-11-2019 16:02:27.357 [cloudfoundry-client-nio-1] ERROR o.s.c.a.deployer.DeployerClient.error - Error updating backing service db-service with error 'Plan does not exist for the my-db-service service'
java.lang.IllegalArgumentException: Plan does not exist for the my-db-service service

Suspecting inconsistency in returned stubbed content.